### ISSUE TITLE
No Api Token showing 

### ISSUE THREAD

**Issue by mycrowman** [bitpay/woocommerce-plugin#55]
Switched webhosts, and now  the API TOKEN information in the plugin setting isnt showing  up. Instead I get this error:
Warning: sprintf(): Too few arguments in /home/nootropicsusa/public_html/wp-content/plugins/bitpay-for-woocommerce/class-wc-gateway-bitpay.php on line 341
![screen shot 2015-05-14 at 1 02 28 am](https://cloud.githubusercontent.com/assets/12447406/7635166/5dc5a54c-fa2d-11e4-8a6b-e41f786b4d19.png)

I have completely uninstalled the plugin on both hosts, and reinstalled on the new host and still having this issue. Could this be server related, if so what do I need them to check?

**Comment by sambohler** [comment]
So the API TOKEN is tied to the server it's generated on.  Uninstalling the plugin should remove the settings forcing you to re-pair:
https://github.com/bitpay/woocommerce-plugin/blob/master/src/uninstall.php#L16

Check your database and delete all bitpay settings: `woocommerce_bitpay_%` in `wp_config` if they are still there.

**Comment by mycrowman** [comment]
Does uninstalling differ from deleting the plugin, if so how do I run the uninstall script? I have search the wp_config and find no references to bitpay.

Thanks

**Comment by sambohler** [comment]
Good to hear about the lack of references in the config.  So it sounds like the plugin is unable to include the template files. It could be a permissions issue if old uid/gid information carried over from the other server.
Instead of using WordPress to deactivate and delete the plugin, delete the plugin folder directly from the filesystem (like with FTP) so no files with troublesome permissions are left behind, and then install the plugin anew via the plugin section of the WordPress dashboard.

**Comment by mycrowman** [comment]
My Man! 
Installed again, just to delete by FTP, then installed Via plugin page and all is working.

Thanks again!
Andrew
