### ISSUE TITLE
Order automatically goes to cancelled

### ISSUE THREAD

**Issue by shawaj** [bitpay/woocommerce-plugin#64]
The orders paid by bitcoin are automatically going to cancelled, instead of going to what we have applied in the settings which is to go to processing.

Any idea why?

**Comment by kleetus** [comment]
could be a variety of things. 

1. check the incoming http POST from BitPay to your notification URL. What's the payload there? If you can't check that, then provide me the invoice id (use a support ticket support@bitpay.com). 
2. check the logs for any other strangeness going on. You can turn on logs for the plugin in the settings for the plugin.

**Comment by shawaj** [comment]
There is an error message left with the order from WooCommerce:

Unpaid order cancelled – time limit reached. Order status changed from Pending Payment to Cancelled.

**Comment by kleetus** [comment]
ok, if the invoice was actually paid with bitcoin (I think you said it was), then I wonder if the instant payment notification from BitPay to your instance of Wordpress received the "confirmed" or "complete" http POST? Does this happen?

**Comment by shawaj** [comment]
How do I check that?

**Comment by kleetus** [comment]
you can turn on logging in the options for the plugin -or- if you submit an email to support@bitpay.com with the invoice id, I can look it up. Don't submit the invoice in this forum.

**Comment by kleetus** [comment]
also, if you turn on logging and there is a problem with BitPay getting that http POST request through, then you won't see anything there. You can curl to your notification URL to check this:

curl -X POST <notification url>

you should at least see something in the logs. From there, the problem should be broken down. If you get  something like a 503, then your notification url is setup correctly

**Comment by shawaj** [comment]
Every payment we have ever had through BitPay has had this same issue. I've just emailed you an example.

We have it set to low, and we have it set to go to pending payment immediately after new order, and then same on paid and confirmed. For complete we have it set to processing.

I'm guessing "complete" corresponds to "payment applied" status on your network?

Thanks

**Comment by kleetus** [comment]
Right, "complete" on BitPay's network means the bitcoin payment for this invoice has 6 confirmations on the blockchain and payment is applied. But, since you are set to "low" transaction speed, you won't get a "complete" status sent to you because low speed transaction settings get confirmed after six confirmations. So rather than sending 2 notifications, "complete" and "confirmed", BitPay just sends "confirmed", yet payment is still applied.

**Comment by shawaj** [comment]
Ok so in a medium or fast payment you would get both, but in low you only get confirmed?

**Comment by shawaj** [comment]
So if we change confirmed to processing it should work?

**Comment by kleetus** [comment]
in medium, you'll get "paid" once we see the bitcoin payment in the Bitcoin P2P transaction memory pool, then after 1 confirmation, you'll get "confirmed". Then after 6 confirmations, you'll get "complete". 

in fast, you'll just get "confirmed" after the tx shows in the memory pools on the network. Then after 6 confirmations, you'll get "complete"

The problem you are experiencing is probably not related to these settings (although these settings are important once the issue is fixed).

I replied to your support request. If your issue is related to this project. I will fix it here and address this issue. Better to take this via support@bitpay.com until we get to the bottom of this.

**Comment by shawaj** [comment]
It might be good to put this explanation somewhere on the main readme as it doesn't explain this fully anywhere else does it? 

In any case will move to email :-)

**Comment by kleetus** [comment]
At the moment, it appears calls to the notification URL are yielding a 500, possibly from a gateway/CDN or the like. If this not the case, then a stack trace from the webserver's error log will tell us what the cause.
